language: java
jdk:
  - openjdk8  
addons:
  sonarcloud:
    organization: "dogonfire"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DogOnFire_Gods