language: java
deploy:
  provider: releases
  api_key: e92d036e275958c01d1a342f577ca959540f8014
  file: Gods.jar
  skip_cleanup: true
  on:
    tags: true
jdk:
  - openjdk8  
script:
 - mvn clean package
 - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash) -f target/site/cobertura/coverage.xml